
spring:
  application:
    name: douyin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/douyin?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8888


